#!/bin/env bash

set -eo pipefail

# shellcheck disable=SC1091
source .config

# Set default value for installation directory
appInstallDir=${APP_INSTALL_DIR:-"/usr/local/bin"}


# Set default value for /etc installation to false by default.
hasConfETC=${HAS_ETC_FILE:-"false"}

# Only set the appETC variable if hasConfETC is true
test "${hasConfETC}" = "false" || appETC=${HAS_ETC_FILE:-"/etc/${appName}.conf"}


